In [ ]:
#program for creating arrays using different functions.

In [1]:
#creating an integer array using arange() function.
import numpy as np #import numpy library

my_arrang = np.arange(15)
print ('the array of integer using arange() function is :\n',my_arrang)




the array of integer using arange() function is :
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [5]:
#creating a float array using arange() function.
my_float = np.arange(19,30, dtype= np.float)
print("the array of decimal numbers using arange() function is:\n", my_float)

the array of decimal numbers using arange() function is:
 [19. 20. 21. 22. 23. 24. 25. 26. 27. 28. 29.]


/var/folders/07/4qgz4xnj28l575f4vrq3z_9m0000gn/T/ipykernel_3052/4065992488.py:2: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  my_float = np.arange(19,30, dtype= np.float)


In [6]:
#creating an integer array using linespace() for equal spacing.
my_line = np.linspace(12,34,5)
print("the array of integers using linspace() function:\n",my_line)

the array of integers using linspace() function:
 [12.  17.5 23.  28.5 34. ]


In [7]:
#creating array using zeros() function.
my_zero = np.zeros((4))
print ("an array using zeros :\n",my_zero)

an array using zeros :
 [0. 0. 0. 0.]
