###One-dimensional Array###

a one-dimesional is an array of elements of similar data type starting from index 0 and ending at n+1. An array can be created using the array() function of numpy library.


In [15]:
# Now we creating a 1-D Array #
# Now we will import numpy libray #

In [18]:
# program to create array from numpy library #
import numpy as np

#creating an array of integers#
my_array = np.array([1,2,3,4,5,6],int)
print("this is integers array:\n ",my_array)

this is integers array:
  [1 2 3 4 5 6]


In [20]:
#creating an array of characters#
my_char = np.array(['a','b','c','d'])
print("this is characters array: \n", my_char)

this is characters array: 
 ['a' 'b' 'c' 'd']


In [21]:
#creating an array of string #
my_string= np.array(['pavan', 'varun', 'anand', 'sayatan', 'adrash'])
print("this is string:\n", my_string)

this is string:
 ['pavan' 'varun' 'anand' 'sayatan' 'adrash']


In [22]:
#creating a float array #
my_float=np.array([1.1,1.3,1.4,1.6])
print("this is flaot array: \n", my_float)

this is flaot array: 
 [1.1 1.3 1.4 1.6]


In [23]:
#creating view() function to create a new array from an existing array#
my_view = my_string.view()
print("using view function to create a new array:\n",my_view)

using view function to create a new array:
 ['pavan' 'varun' 'anand' 'sayatan' 'adrash']


In [24]:
#using copy() function to create a new array from an existing array #
my_copy = my_float.copy()
print("using copy function to create a new array :\n", my_copy)

using copy function to create a new array :
 [1.1 1.3 1.4 1.6]


This is demonstrates different methods of creating arrays of different data types, such as integer,decimal,character,string,float.